class ActivityLogModel {
  final int? id;
  final String judul;
  final DateTime? createdAt;
  final DateTime tanggal;
  final String user;
  final String type;

  ActivityLogModel({
    this.id,
    required this.judul,
    this.createdAt,
    required this.tanggal,
    required this.user,
    required this.type,
  });

  factory ActivityLogModel.fromJson(Map<String, dynamic> json) {
    return ActivityLogModel(
      id: json['id'],
      judul: json['judul'] ?? '',
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : null,
      tanggal: json['tanggal'] != null
          ? DateTime.parse(json['tanggal'])
          : DateTime.now(),
      user: json['user'] ?? '',
      type: json['type'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // id is usually auto-generated
      'judul': judul,
      'tanggal': tanggal.toIso8601String(),
      'user': user,
      'type': type,
      // created_at is usually auto-generated by DB
    };
  }
}
