import 'package:jawara_pintar_kel_5/models/kegiatan/kegiatan_model.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class KegiatanService {
  final SupabaseClient _supabase = Supabase.instance.client;
  final String _tableName = 'kegiatan';

  /// Fetch semua kegiatan
  Future<List<KegiatanModel>> getKegiatan() async {
    try {
      final response =
          await _supabase.from(_tableName).select().order('tanggal', ascending: false);
      return List<KegiatanModel>.from(
          response.map((json) => KegiatanModel.fromMap(json)));
    } catch (e) {
      throw Exception('Error fetching kegiatan: $e');
    }
  }

  /// Fetch kegiatan by ID
  Future<KegiatanModel> getKegiatanById(int id) async {
    try {
      final response = await _supabase
          .from(_tableName)
          .select()
          .eq('id', id)
          .single();
      return KegiatanModel.fromMap(response);
    } catch (e) {
      throw Exception('Error fetching kegiatan by id: $e');
    }
  }

  /// Create kegiatan baru
  Future<KegiatanModel> createKegiatan(KegiatanModel kegiatan) async {
    try {
      // Omitting id and created_at because they are generated by the database
      final Map<String, dynamic> insertData = kegiatan.toMap()
        ..remove('id')
        ..remove('created_at');

      final response = await _supabase
          .from(_tableName)
          .insert(insertData)
          .select()
          .single();

      return KegiatanModel.fromMap(response);
    } catch (e) {
      throw Exception('Error creating kegiatan: $e');
    }
  }

  /// Update kegiatan
  Future<KegiatanModel> updateKegiatan(int id, KegiatanModel kegiatan) async {
    try {
      // Omitting id and created_at because they should not be updated
      final Map<String, dynamic> updateData = kegiatan.toMap()
        ..remove('id')
        ..remove('created_at');

      final response = await _supabase
          .from(_tableName)
          .update(updateData)
          .eq('id', id)
          .select()
          .single();

      return KegiatanModel.fromMap(response);
    } catch (e) {
      throw Exception('Error updating kegiatan: $e');
    }
  }

  /// Delete kegiatan
  Future<void> deleteKegiatan(int id) async {
    try {
      await _supabase.from(_tableName).delete().eq('id', id);
    } catch (e) {
      throw Exception('Error deleting kegiatan: $e');
    }
  }
}
